import java.util.List;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashir
 */
public class BookingPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingPage.class.getName());

    /**
     * Creates new form BookingPage
     */
    private AirlineSystem.Flight flight;

    public BookingPage() {
        initComponents();
        cmbClass.removeAllItems(); // clear default items

        // If flight is null (default constructor), we can show all options
        cmbClass.addItem("First");
        cmbClass.addItem("Business");
        cmbClass.addItem("Economy");
    }

    // In constructor with flight
    public BookingPage(AirlineSystem.Flight selectedFlight) {
        this.flight = selectedFlight;
        initComponents();
        cmbClass.removeAllItems(); // clear default items
        populateFlightDetails();    // populate based on available seats
    }

    private void populateFlightDetails() {
        lblSelectedFlightID.setText(flight.getFlightID());
        cmbClass.removeAllItems(); // clear previous items

        if (flight.getFirstSeats() > 0) cmbClass.addItem("First");
        if (flight.getBusinessSeats() > 0) cmbClass.addItem("Business");
        if (flight.getEconomySeats() > 0) cmbClass.addItem("Economy");

        // Set first item as selected
        if (cmbClass.getItemCount() > 0) cmbClass.setSelectedIndex(0);

        updatePriceLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBookingPage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPassengerName = new javax.swing.JLabel();
        txtPassengerName = new javax.swing.JTextField();
        lblPassengerCNIC = new javax.swing.JLabel();
        txtPassengerCNIC = new javax.swing.JTextField();
        lblPassengerContact = new javax.swing.JLabel();
        txtPassengerContact = new javax.swing.JTextField();
        lblFlightIDText = new javax.swing.JLabel();
        lblSelectedFlightID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbClass = new javax.swing.JComboBox<>();
        lblPriceText = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnConfirmBooking = new javax.swing.JButton();
        btnCancelBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking Page");
        getContentPane().setBackground(new Color(240, 245, 255));

        lblBookingPage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBookingPage.setForeground(Color.BLACK);
        lblBookingPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookingPage.setText("Booking Page");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Flight"));
        jPanel1.setBackground(new Color(220, 230, 250));

        lblPassengerName.setText("Passenger Name:");
        lblPassengerName.setForeground(Color.BLACK);

        lblPassengerCNIC.setText("CNIC:");
        lblPassengerCNIC.setForeground(Color.BLACK);

        txtPassengerCNIC.setText("12345-1234567-1");

        lblPassengerContact.setText("Contact No:");
        lblPassengerContact.setForeground(Color.BLACK);

        lblFlightIDText.setText("Flight ID:");
        lblFlightIDText.setForeground(Color.BLACK);

        lblSelectedFlightID.setText("default");
        lblSelectedFlightID.setForeground(Color.BLACK);

        jLabel1.setText("Select Class:");
        jLabel1.setForeground(Color.BLACK);

        cmbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClass.addActionListener(this::cmbClassActionPerformed);

        lblPriceText.setText("Price:");
        lblPriceText.setForeground(Color.BLACK);

        lblPrice.setText("Default");
        lblPrice.setForeground(Color.BLACK);

        btnConfirmBooking.setText("Confirm Booking");
        btnConfirmBooking.setBackground(new Color(200, 210, 230));
        btnConfirmBooking.setForeground(Color.BLACK);
        btnConfirmBooking.setFocusPainted(false);
        btnConfirmBooking.setPreferredSize(new Dimension(140, 30));
        btnConfirmBooking.addActionListener(this::btnConfirmBookingActionPerformed);

        btnCancelBooking.setText("Cancel");
        btnCancelBooking.setBackground(new Color(200, 210, 230));
        btnCancelBooking.setForeground(Color.BLACK);
        btnCancelBooking.setFocusPainted(false);
        btnCancelBooking.setPreferredSize(new Dimension(140, 30));
        btnCancelBooking.addActionListener(this::btnCancelBookingActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPassengerName)
                                        .addComponent(lblPassengerCNIC)
                                        .addComponent(lblPassengerContact)
                                        .addComponent(lblFlightIDText)
                                        .addComponent(jLabel1)
                                        .addComponent(lblPriceText))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPassengerName)
                                        .addComponent(txtPassengerCNIC)
                                        .addComponent(txtPassengerContact)
                                        .addComponent(lblSelectedFlightID)
                                        .addComponent(cmbClass, 0, 150, Short.MAX_VALUE)
                                        .addComponent(lblPrice))
                                .addContainerGap(30, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(50, Short.MAX_VALUE)
                                .addComponent(btnConfirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnCancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPassengerName)
                                        .addComponent(txtPassengerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPassengerCNIC)
                                        .addComponent(txtPassengerCNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPassengerContact)
                                        .addComponent(txtPassengerContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFlightIDText)
                                        .addComponent(lblSelectedFlightID))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPriceText)
                                        .addComponent(lblPrice))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnConfirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(lblBookingPage)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblBookingPage)
                                .addGap(10, 10, 10)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassActionPerformed
        updatePriceLabel();
    }//GEN-LAST:event_cmbClassActionPerformed

    private void updatePriceLabel() {
        String seatClass = (String) cmbClass.getSelectedItem();
        if (seatClass != null) {
            double price = 0;

            if (flight != null) {
                price = flight.getBaseFare();
                switch (seatClass) {
                    case "First": price *= 2; break;
                    case "Business": price *= 1.5; break;
                }
            } else {
                // Default prices if no flight is selected
                switch (seatClass) {
                    case "First": price = 200; break;       // example base price
                    case "Business": price = 150; break;
                    case "Economy": price = 100; break;
                }
            }

            lblPrice.setText(String.format("%.2f", price));
        }
    }


    private void btnCancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBookingActionPerformed
        this.dispose();
        new SearchFlightsPage().setVisible(true);
    }//GEN-LAST:event_btnCancelBookingActionPerformed

    private void btnConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {
        if (flight == null) {
            JOptionPane.showMessageDialog(this, "No flight selected. Cannot confirm booking.");
            return;
        }

        String name = txtPassengerName.getText().trim();
        String cnic = txtPassengerCNIC.getText().trim();
        String contact = txtPassengerContact.getText().trim();
        String seatClass = (String) cmbClass.getSelectedItem();

        if (name.isEmpty() || cnic.isEmpty() || contact.isEmpty() || seatClass == null) {
            JOptionPane.showMessageDialog(this, "Please fill all fields and select a class.");
            return;
        }

        boolean booked = false;
        switch (seatClass) {
            case "First": if (flight.getFirstSeats() > 0) { flight.setFirstSeats(flight.getFirstSeats()-1); booked = true;} break;
            case "Business": if (flight.getBusinessSeats() > 0) { flight.setBusinessSeats(flight.getBusinessSeats()-1); booked = true;} break;
            case "Economy": if (flight.getEconomySeats() > 0) { flight.setEconomySeats(flight.getEconomySeats()-1); booked = true;} break;
        }

        if (!booked) {
            JOptionPane.showMessageDialog(this, seatClass + " class is full.");
            return;
        }
        List<AirlineSystem.Flight> flights = AirlineSystem.FlightHandler.getAllFlights();
        for (int i = 0; i < flights.size(); i++) {
            if (flights.get(i).getFlightID().equalsIgnoreCase(flight.getFlightID())) {
                flights.set(i, flight);
                break;
            }
        }
        AirlineSystem.FlightHandler.updateFlights(flights);

        String ticketID = "TKT" + System.currentTimeMillis();
        String seatNo = seatClass.charAt(0) + "-" + (int)(Math.random() * 40 + 1);
        String price = lblPrice.getText();
        String passengerID = "PAX" + System.currentTimeMillis();
        String[] passengerData = { passengerID, name, "0", "N/A", contact };
        DataManager.appendPassenger(passengerData);


        // Open Payment Page
        String[] ticketData = {
                ticketID,
                txtPassengerName.getText().trim(),  // Passenger Name
                txtPassengerCNIC.getText().trim(),  // CNIC
                txtPassengerContact.getText().trim(), // Contact
                flight.getFlightID(),               // Flight ID
                flight.getSource(),                 // Source
                flight.getDestination(),            // Destination
                flight.getDate(),                   // Date
                flight.getTime(),                   // Time
                seatClass,                          // Class
                seatNo,                             // Seat
                lblPrice.getText()                  // Price
        };

        PaymentPage paymentPage = new PaymentPage(ticketData);
        paymentPage.setVisible(true);

        this.dispose();

        // rest of your booking logic...
    }
//GEN-LAST:event_btnConfirmBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelBooking;
    private javax.swing.JButton btnConfirmBooking;
    private javax.swing.JComboBox<String> cmbClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBookingPage;
    private javax.swing.JLabel lblFlightIDText;
    private javax.swing.JLabel lblPassengerCNIC;
    private javax.swing.JLabel lblPassengerContact;
    private javax.swing.JLabel lblPassengerName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPriceText;
    private javax.swing.JLabel lblSelectedFlightID;
    private javax.swing.JTextField txtPassengerCNIC;
    private javax.swing.JTextField txtPassengerContact;
    private javax.swing.JTextField txtPassengerName;
    // End of variables declaration//GEN-END:variables
}
