import java.util.ArrayList;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashir
 */
public class MyBookingsPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyBookingsPage.class.getName());

    // Load all bookings from DataManager and display in the table
    private void loadMyBookings() {
        // In a real app, you'd pass the passenger ID to this page
        // For now, we'll show all bookings
        ArrayList<String[]> tickets = DataManager.readTickets();

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) tblBookings.getModel();

        // Clear existing rows
        model.setRowCount(0);

        // Set column names
        model.setColumnIdentifiers(new String[]{
                "Ticket ID", "Passenger ID", "Name", "CNIC", "Contact",
                "Flight ID", "Class", "Seat", "Price"
        });

        // Add rows
        for (String[] ticket : tickets) {
            model.addRow(ticket);
        }
    }

    /**
     * Creates new form MyBookingsPage
     */
    public MyBookingsPage() {
        initComponents();
        loadMyBookings();
        tblBookings.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Main container panel
        JPanel mainPanel = new JPanel();
        mainPanel.setBackground(new Color(245, 245, 245)); // light grey background
        mainPanel.setBorder(new EmptyBorder(20, 20, 20, 20));
        mainPanel.setLayout(new BorderLayout(0, 20));

        // Title label
        titleMyBookings = new JLabel("My Bookings");
        titleMyBookings.setFont(new Font("Segoe UI", Font.BOLD, 28));
        titleMyBookings.setHorizontalAlignment(SwingConstants.CENTER);
        titleMyBookings.setForeground(new Color(33, 37, 41)); // dark color
        mainPanel.add(titleMyBookings, BorderLayout.NORTH);

        // Table panel
        JPanel tablePanel = new JPanel(new BorderLayout());
        tablePanel.setBackground(Color.WHITE);
        tablePanel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200)),
                "Your Bookings",
                TitledBorder.LEADING,
                TitledBorder.TOP,
                new Font("Segoe UI", Font.PLAIN, 14),
                new Color(60, 63, 65)
        ));

        tblBookings = new JTable();
        tblBookings.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tblBookings.setRowHeight(25);
        tblBookings.setFillsViewportHeight(true);
        tblBookings.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblBookings.getTableHeader().setBackground(new Color(52, 152, 219));
        tblBookings.getTableHeader().setForeground(Color.WHITE);

        scrollBookings = new JScrollPane(tblBookings);
        tablePanel.add(scrollBookings, BorderLayout.CENTER);

        mainPanel.add(tablePanel, BorderLayout.CENTER);

        // Buttons panel
        JPanel buttonsPanel = new JPanel();
        buttonsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 30, 10));
        buttonsPanel.setBackground(new Color(245, 245, 245));


        btnBack = new JButton("Back");
        btnBack.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        btnBack.setBackground(new Color(52, 152, 219));
        btnBack.setForeground(Color.WHITE);
        btnBack.setFocusPainted(false);
        btnBack.setPreferredSize(new Dimension(150, 35));
        btnBack.addActionListener(this::btnBackActionPerformed);

        buttonsPanel.add(btnBack);

        mainPanel.add(buttonsPanel, BorderLayout.SOUTH);

        // Add main panel to frame
        getContentPane().add(mainPanel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Bookings");
        setSize(900, 500);
        setLocationRelativeTo(null); // center screen
    }// </editor-fold>//GEN-END:initComponents



    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new UserMainPage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new MyBookingsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane scrollBookings;
    private javax.swing.JTable tblBookings;
    private javax.swing.JLabel titleMyBookings;
    // End of variables declaration//GEN-END:variables
}
