import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ashir
 */
public class PaymentPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentPage.class.getName());

    /**
     * Creates new form PaymentPage
     */
    public PaymentPage() {
        initComponents();
    }
    public String[] ticketData;

    /**
     * Constructor: Uses index 0 for Ticket ID (previously FlightID) and index 11 for Amount.
     */
    public PaymentPage(String[] ticketData) {
        this(); // call default constructor to initialize UI
        this.ticketData = ticketData;

        // populate fields for confirmation
        // *** USING txtTicketID (was txtFlightID) and index 0 (assuming it holds the ID)
        txtTicketID.setText(ticketData[0]); // Ticket ID
        txtAmount.setText(ticketData[11]);  // Price

        // Disable text fields that hold read-only data
        txtTicketID.setEditable(false);
        txtAmount.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTicketID = new javax.swing.JLabel(); // CHANGED FROM lblFlightID
        txtTicketID = new javax.swing.JTextField(); // CHANGED FROM txtFlightID
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblCardNumber = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        lblCardHolder = new javax.swing.JLabel();
        txtCardHolder = new javax.swing.JTextField();
        lblExpiry = new javax.swing.JLabel();
        txtExpiry = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setBackground(new Color(245, 250, 255));

        lblTitle.setText("Payment");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 24));
        lblTitle.setForeground(new Color(30, 30, 60));
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);

        // --- LABEL CHANGE HERE ---
        lblTicketID.setText("Ticket ID"); // CHANGED FROM "FlightID"
        lblTicketID.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblTicketID.setForeground(new Color(50, 50, 80));

        lblAmount.setText("Amount");
        lblAmount.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblAmount.setForeground(new Color(50, 50, 80));

        lblCardNumber.setText("Card Number:");
        lblCardNumber.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblCardNumber.setForeground(new Color(50, 50, 80));

        lblCardHolder.setText("Card Holder:");
        lblCardHolder.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblCardHolder.setForeground(new Color(50, 50, 80));

        lblExpiry.setText("Expiry(MM/YY):");
        lblExpiry.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblExpiry.setForeground(new Color(50, 50, 80));

        // --- TEXT FIELD NAME CHANGE HERE ---
        txtTicketID.setBackground(new Color(255, 255, 255)); // CHANGED FROM txtFlightID
        txtAmount.setBackground(new Color(255, 255, 255));
        txtCardNumber.setBackground(new Color(255, 255, 255));
        txtCardHolder.setBackground(new Color(255, 255, 255));
        txtExpiry.setBackground(new Color(255, 255, 255));

        btnPay.setText("Pay");
        btnPay.setBackground(new Color(75, 150, 255));
        btnPay.setForeground(Color.WHITE);
        btnPay.setFocusPainted(false);
        btnPay.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnPay.addActionListener(this::btnPayActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.setBackground(new Color(200, 50, 50));
        btnCancel.setForeground(Color.WHITE);
        btnCancel.setFocusPainted(false);
        btnCancel.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        // GroupLayout for main content
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addComponent(lblTitle)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTicketID) // CHANGED FROM lblFlightID
                                        .addComponent(lblAmount)
                                        .addComponent(lblCardNumber)
                                        .addComponent(lblCardHolder)
                                        .addComponent(lblExpiry))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTicketID, 150, 150, 150) // CHANGED FROM txtFlightID
                                        .addComponent(txtAmount, 150, 150, 150)
                                        .addComponent(txtCardNumber, 150, 150, 150)
                                        .addComponent(txtCardHolder, 150, 150, 150)
                                        .addComponent(txtExpiry, 150, 150, 150)))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPay, 100, 100, 100)
                                .addGap(40)
                                .addComponent(btnCancel, 100, 100, 100))
        );

        layout.setVerticalGroup(
                layout.createSequentialGroup()
                        .addGap(20)
                        .addComponent(lblTitle)
                        .addGap(20)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTicketID) // CHANGED FROM lblFlightID
                                .addComponent(txtTicketID, 25, 25, 25)) // CHANGED FROM txtFlightID
                        .addGap(10)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAmount)
                                .addComponent(txtAmount, 25, 25, 25))
                        .addGap(10)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCardNumber)
                                .addComponent(txtCardNumber, 25, 25, 25))
                        .addGap(10)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCardHolder)
                                .addComponent(txtCardHolder, 25, 25, 25))
                        .addGap(10)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblExpiry)
                                .addComponent(txtExpiry, 25, 25, 25))
                        .addGap(20)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPay, 30, 30, 30)
                                .addComponent(btnCancel, 30, 30, 30))
                        .addGap(20)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {
        String ticketID = txtTicketID.getText().trim(); // CHANGED FROM flightID and txtFlightID
        String amountStr = txtAmount.getText().trim();
        String cardNumber = txtCardNumber.getText().trim();
        String cardHolder = txtCardHolder.getText().trim();
        String expiry = txtExpiry.getText().trim();

        if (ticketID.isEmpty() || amountStr.isEmpty() || cardNumber.isEmpty() ||
                cardHolder.isEmpty() || expiry.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double amount;
        try {
            amount = Double.parseDouble(amountStr);
            if (amount <= 0) {
                JOptionPane.showMessageDialog(this, "Amount must be positive", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount format", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cardNumber.length() < 12) {
            JOptionPane.showMessageDialog(this, "Invalid card number. Must be at least 12 digits.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!expiry.matches("\\d{2}/\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Invalid expiry format. Use MM/YY (e.g., 03/27)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Payment success message
        JOptionPane.showMessageDialog(this,
                String.format("Payment of $%.2f for Ticket ID %s processed successfully!", amount, ticketID), // CHANGED TO Ticket ID
                "Payment Success",
                JOptionPane.INFORMATION_MESSAGE);

        // Close payment page
        this.dispose();

        // Open TicketSummaryPage with ticket data
        try {
            TicketSummaryPage ticketSummary = new TicketSummaryPage(this.ticketData);
            ticketSummary.setVisible(true);
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Could not open TicketSummaryPage", e);
            JOptionPane.showMessageDialog(null, "Payment succeeded, but could not open the summary page.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to cancel the payment?",
                "Confirm Cancel",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            try {
                new UserMainPage().setVisible(true);
            } catch (Exception e) {
                logger.log(java.util.logging.Level.SEVERE, "Could not open UserMainPage after cancel", e);
            }
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new PaymentPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCardHolder;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblExpiry;
    private javax.swing.JLabel lblTicketID;
    private javax.swing.JLabel lblTitle;
    public javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCardHolder;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtExpiry;
    public javax.swing.JTextField txtTicketID;
    // End of variables declaration//GEN-END:variables
}