import javax.swing.*;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashir
 */
public class RegisterPassengerPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterPassengerPage.class.getName());

    /**
     * Creates new form RegisterPassengerPage
     */
    public RegisterPassengerPage() {
        initComponents();
        getContentPane().setBackground(new Color(230, 240, 250)); // light soft blue background
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        lblRegisterTitle = new JLabel();
        lblName = new JLabel();
        txtName = new JTextField();
        lblAge = new JLabel();
        txtAge = new JTextField();
        lblGender = new JLabel();
        cmbGender = new JComboBox<>();
        lblContact = new JLabel();
        txtContact = new JTextField();
        btnRegister = new JButton();
        btnBack = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(450, 400));
        setResizable(false);

        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 22));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Airline System");

        lblRegisterTitle.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        lblRegisterTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblRegisterTitle.setText("Passenger Registration");

        lblName.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblName.setText("Name:");

        lblAge.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblAge.setText("Age:");

        lblGender.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblGender.setText("Gender:");

        cmbGender.setModel(new DefaultComboBoxModel<>(new String[]{"Male", "Female"}));
        cmbGender.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        lblContact.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblContact.setText("Contact:");

        txtName.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtName.setPreferredSize(new Dimension(200, 30));

        txtAge.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtAge.setPreferredSize(new Dimension(200, 30));

        txtContact.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtContact.setPreferredSize(new Dimension(200, 30));

        btnRegister.setText("Register");
        btnRegister.setBackground(new Color(120, 160, 200));
        btnRegister.setForeground(Color.WHITE);
        btnRegister.setFocusPainted(false);
        btnRegister.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        btnBack.setText("Back to Login");
        btnBack.setBackground(new Color(180, 180, 180));
        btnBack.setForeground(Color.BLACK);
        btnBack.setFocusPainted(false);
        btnBack.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnBack.addActionListener(this::btnBackActionPerformed);

        // Layout
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegisterTitle, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblName)
                                        .addComponent(lblAge)
                                        .addComponent(lblGender)
                                        .addComponent(lblContact))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(txtName, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAge, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbGender, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtContact, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegister, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
        );

        layout.setVerticalGroup(
                layout.createSequentialGroup()
                        .addGap(20)
                        .addComponent(jLabel1)
                        .addGap(10)
                        .addComponent(lblRegisterTitle)
                        .addGap(25)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(txtName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(15)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAge)
                                .addComponent(txtAge, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(15)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblGender)
                                .addComponent(cmbGender, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(15)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblContact)
                                .addComponent(txtContact, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(30)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRegister, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBack, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                        .addGap(20)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText().trim();
        String ageStr = txtAge.getText().trim();
        String gender = (String) cmbGender.getSelectedItem();
        String contact = txtContact.getText().trim();

        if (name.isEmpty() || ageStr.isEmpty() || contact.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int age;
        try {
            age = Integer.parseInt(ageStr);
            if (age <= 0 || age > 150) {
                JOptionPane.showMessageDialog(this, "Please enter a valid age (1-150)", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid age number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Generate Passenger ID
        String passengerID = "P" + System.currentTimeMillis();

        // Create passenger data array
        String[] passengerData = {
                passengerID,
                name.replace(" ", "_"),
                String.valueOf(age),
                gender,
                contact,
                "0.0"
        };

        // Save to file
        DataManager.appendPassenger(passengerData);

        // Show success message with Passenger ID
        String message = String.format(
                "Registration Successful!\n\nYour Passenger ID: %s\n\nPlease remember this ID for login.",
                passengerID
        );
        JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);

        // Go back to login page
        this.dispose();
        new UserLoginPage().setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserLoginPage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterPassengerPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnBack;
    private JButton btnRegister;
    private JComboBox<String> cmbGender;
    private JLabel jLabel1;
    private JLabel lblAge;
    private JLabel lblContact;
    private JLabel lblGender;
    private JLabel lblName;
    private JLabel lblRegisterTitle;
    private JTextField txtAge;
    private JTextField txtContact;
    private JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
