import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashir
 */
public class SearchFlightsPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchFlightsPage.class.getName());

    /**
     * Creates new form SearchFlightsPage
     */
    public SearchFlightsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearchFlights = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSearchSource = new javax.swing.JLabel();
        txtSearchSource = new javax.swing.JTextField();
        btnSearchDestination = new javax.swing.JLabel();
        txtSearchDestination = new javax.swing.JTextField();
        btnSearchDate = new javax.swing.JLabel();
        txtSearchDate = new javax.swing.JTextField();
        btnSearchNow = new javax.swing.JButton();
        scrollSearchResults = new javax.swing.JScrollPane();
        tblSearchResults = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnBookSelected = new javax.swing.JButton();
        btnSearchBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Flights");
        getContentPane().setBackground(new Color(240, 245, 255));

        lblSearchFlights.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSearchFlights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchFlights.setText("Search Flights");
        lblSearchFlights.setForeground(Color.BLACK);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setBackground(new Color(220, 230, 250));

        btnSearchSource.setText("Source:");
        btnSearchSource.setForeground(Color.BLACK);

        btnSearchDestination.setText("Destination:");
        btnSearchDestination.setForeground(Color.BLACK);

        btnSearchDate.setText("Date:");
        btnSearchDate.setForeground(Color.BLACK);

        txtSearchDate.setText("YYYY-MM-DD");

        btnSearchNow.setText("Search");
        btnSearchNow.setBackground(new Color(200, 210, 230));
        btnSearchNow.setForeground(Color.BLACK);
        btnSearchNow.setFocusPainted(false);
        btnSearchNow.addActionListener(this::btnSearchNowActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnSearchSource)
                                .addGap(10, 10, 10)
                                .addComponent(txtSearchSource, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnSearchDestination)
                                .addGap(10, 10, 10)
                                .addComponent(txtSearchDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnSearchDate)
                                .addGap(10, 10, 10)
                                .addComponent(txtSearchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnSearchNow, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSearchSource)
                                        .addComponent(txtSearchSource, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearchDestination)
                                        .addComponent(txtSearchDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearchDate)
                                        .addComponent(txtSearchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearchNow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(10, Short.MAX_VALUE))
        );

        tblSearchResults.setModel(new DefaultTableModel(
                new Object [][] {},
                new String [] {
                        "Flight ID", "Source", "Destination", "Date", "Time", "Base Fare", "First Seats", "Business Seats", "Economy Seats"
                }
        ));
        tblSearchResults.setFillsViewportHeight(true);
        tblSearchResults.setRowHeight(25);
        tblSearchResults.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        scrollSearchResults.setViewportView(tblSearchResults);
        scrollSearchResults.setPreferredSize(new Dimension(900, 150));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setBackground(new Color(220, 230, 250));

        btnBookSelected.setText("Book Selected");
        btnBookSelected.setBackground(new Color(200, 210, 230));
        btnBookSelected.setForeground(Color.BLACK);
        btnBookSelected.setFocusPainted(false);
        btnBookSelected.setPreferredSize(new Dimension(140, 30));
        btnBookSelected.addActionListener(this::btnBookSelectedActionPerformed);

        btnSearchBack.setText("Back");
        btnSearchBack.setBackground(new Color(200, 210, 230));
        btnSearchBack.setForeground(Color.BLACK);
        btnSearchBack.setFocusPainted(false);
        btnSearchBack.setPreferredSize(new Dimension(140, 30));
        btnSearchBack.addActionListener(this::btnSearchBackActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btnBookSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                                .addComponent(btnSearchBack, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBookSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearchBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(50, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(lblSearchFlights)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scrollSearchResults)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblSearchFlights)
                                .addGap(15, 15, 15)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(scrollSearchResults, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNowActionPerformed
        String src = txtSearchSource.getText().trim();
        String dst = txtSearchDestination.getText().trim();
        String date = txtSearchDate.getText().trim();

        ArrayList<AirlineSystem.Flight> flights = new ArrayList<>(AirlineSystem.FlightHandler.getAllFlights());
        DefaultTableModel model = (DefaultTableModel) tblSearchResults.getModel();
        model.setRowCount(0);

        for (AirlineSystem.Flight f : flights) {
            boolean matches = f.getSource().equalsIgnoreCase(src) &&
                    f.getDestination().equalsIgnoreCase(dst) &&
                    f.getDate().equals(date);
            if (matches) {
                model.addRow(new Object[]{
                        f.getFlightID(), f.getSource(), f.getDestination(),
                        f.getDate(), f.getTime(), f.getBaseFare(),
                        f.getFirstSeats(), f.getBusinessSeats(), f.getEconomySeats()
                });
            }
        }

        if (model.getRowCount() == 0) {
            scrollSearchResults.setPreferredSize(new Dimension(900, 150));
            JOptionPane.showMessageDialog(this, "No flights found for the selected criteria.");
        } else {
            int height = Math.min(model.getRowCount() * 25 + 25, 300);
            scrollSearchResults.setPreferredSize(new Dimension(900, height));
            pack();
        }
    }//GEN-LAST:event_btnSearchNowActionPerformed

    private void btnSearchBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBackActionPerformed
        this.dispose();
        new UserMainPage().setVisible(true);
    }//GEN-LAST:event_btnSearchBackActionPerformed

    private void btnBookSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSelectedActionPerformed
        int selectedRow = tblSearchResults.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a flight to book.");
            return;
        }

        String flightID = tblSearchResults.getValueAt(selectedRow, 0).toString();
        AirlineSystem.Flight flight = AirlineSystem.FlightHandler.getFlightByID(flightID);
        if (flight == null) {
            JOptionPane.showMessageDialog(this, "Selected flight not found.");
            return;
        }

        new BookingPage(flight).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) UIManager.setLookAndFeel(info.getClassName());
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchFlightsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookSelected;
    private javax.swing.JButton btnSearchBack;
    private javax.swing.JLabel btnSearchDate;
    private javax.swing.JLabel btnSearchDestination;
    private javax.swing.JButton btnSearchNow;
    private javax.swing.JLabel btnSearchSource;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSearchFlights;
    private javax.swing.JScrollPane scrollSearchResults;
    private javax.swing.JTable tblSearchResults;
    private javax.swing.JTextField txtSearchDate;
    private javax.swing.JTextField txtSearchDestination;
    private javax.swing.JTextField txtSearchSource;
    // End of variables declaration//GEN-END:variables
}
