import java.awt.Font;
import java.awt.Color;
import javax.swing.BorderFactory;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashir
 */
public class TicketSummaryPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicketSummaryPage.class.getName());

    /**
     * Creates new form TicketSummaryPage
     */
    private String[] ticketData;

    public TicketSummaryPage() {
        initComponents();
    }

    public TicketSummaryPage(String[] ticketData) {
        this.ticketData = ticketData; // <-- assign the ticket data first

        initComponents();

        // Modernizing UI
        getContentPane().setBackground(new Color(245, 250, 255));

        txtTicketDetails.setEditable(false);
        txtTicketDetails.setFont(new Font("Monospaced", Font.PLAIN, 14));
        txtTicketDetails.setLineWrap(true);
        txtTicketDetails.setWrapStyleWord(true);
        txtTicketDetails.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 1));
        txtTicketDetails.setBackground(new Color(255, 255, 255));
        txtTicketDetails.setForeground(new Color(30, 30, 60));
        txtTicketDetails.setMargin(new java.awt.Insets(10, 10, 10, 10));

        lblTicketTitle.setFont(new Font("Segoe UI", Font.BOLD, 26));
        lblTicketTitle.setForeground(new Color(30, 60, 120));

        btnPrintTicket.setBackground(new Color(0, 180, 0));
        btnPrintTicket.setForeground(Color.WHITE);
        btnPrintTicket.setFocusPainted(false);
        btnPrintTicket.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnPrintTicket.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        btnDone.setBackground(new Color(200, 50, 50));
        btnDone.setForeground(Color.WHITE);
        btnDone.setFocusPainted(false);
        btnDone.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnDone.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        // Set ticket details
        txtTicketDetails.setText(
                "Ticket ID: " + ticketData[0] + "\n" +
                        "Passenger: " + ticketData[1] + "\n" +
                        "CNIC: " + ticketData[2] + "\n" +
                        "Contact: " + ticketData[3] + "\n" +
                        "Flight ID: " + ticketData[4] + "\n" +
                        "Source: " + ticketData[5] + "\n" +
                        "Destination: " + ticketData[6] + "\n" +
                        "Date: " + ticketData[7] + "\n" +
                        "Time: " + ticketData[8] + "\n" +
                        "Class: " + ticketData[9] + "\n" +
                        "Seat: " + ticketData[10] + "\n" +
                        "Price: " + ticketData[11] + "\n"
        );
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTicketTitle = new javax.swing.JLabel();
        scrollTicketDetails = new javax.swing.JScrollPane();
        txtTicketDetails = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnSaveTicket = new javax.swing.JButton();
        btnPrintTicket = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket Summary");

        lblTicketTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTicketTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTicketTitle.setText("TICKET SUMMARY");

        txtTicketDetails.setColumns(20);
        txtTicketDetails.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtTicketDetails.setRows(5);
        scrollTicketDetails.setViewportView(txtTicketDetails);

        jPanel1.setOpaque(false);

        btnSaveTicket.setText("Save Ticket to File");
        btnSaveTicket.addActionListener(this::btnSaveTicketActionPerformed);

        btnPrintTicket.setText("Print Ticket");
        btnPrintTicket.addActionListener(this::btnPrintTicketActionPerformed);

        btnDone.setText("Done");
        btnDone.addActionListener(this::btnDoneActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnSaveTicket)
                                .addGap(100, 100, 100)
                                .addComponent(btnPrintTicket)
                                .addGap(100, 100, 100)
                                .addComponent(btnDone)
                                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSaveTicket, 40, 40, 40)
                                        .addComponent(btnPrintTicket, 40, 40, 40)
                                        .addComponent(btnDone, 40, 40, 40))
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTicketTitle, 600, 600, 600)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(scrollTicketDetails, 600, 600, 600)
                                .addContainerGap(50, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jPanel1, 600, 600, 600)
                                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblTicketTitle)
                                .addGap(20, 20, 20)
                                .addComponent(scrollTicketDetails, 250, 250, 250)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, 80, 80, 80)
                                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveTicketActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            java.io.FileWriter fw = new java.io.FileWriter("tickets.txt", true); // append mode

            // Auto-generate Passenger ID
            String passengerID = "PAX" + System.currentTimeMillis();

            // Format: TKT|PAX|Name|CNIC|Contact|FlightID|Class|Seat|Price
            String line =
                    ticketData[0] + "|" +        // Ticket ID
                            passengerID + "|" +          // Auto Passenger ID
                            ticketData[1] + "|" +        // Name
                            ticketData[2] + "|" +        // CNIC
                            ticketData[3] + "|" +        // Contact
                            ticketData[4] + "|" +        // Flight ID
                            ticketData[9] + "|" +        // Class
                            ticketData[10] + "|" +       // Seat
                            ticketData[11];              // Price

            fw.write(line + System.lineSeparator());
            fw.close();

            javax.swing.JOptionPane.showMessageDialog(this, "Ticket saved!");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
//GEN-LAST:event_btnSaveTicketActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserMainPage().setVisible(true);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnPrintTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintTicketActionPerformed
        // TODO add your handling code here:
        try {
            boolean printed = txtTicketDetails.print();
            if (printed) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ticket printed successfully!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Printing canceled.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error printing ticket: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPrintTicketActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnPrintTicket;
    private javax.swing.JButton btnSaveTicket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTicketTitle;
    private javax.swing.JScrollPane scrollTicketDetails;
    private javax.swing.JTextArea txtTicketDetails;
    // End of variables declaration//GEN-END:variables
}
