import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashir
 */
public class UserLoginPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserLoginPage.class.getName());

    /**
     * Creates new form UserLoginPage
     */
    public UserLoginPage() {
        initComponents();
        getContentPane().setBackground(new Color(230, 240, 250)); // light soft blue background
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new JLabel();
        lblTitle = new JLabel();
        lblPassengerID = new JLabel();
        txtPassengerID = new JTextField();
        btnLogin = new JButton();
        lblNewUser = new JLabel();
        btnRegisterSwitch = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(450, 350));
        setResizable(false);

        jLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
        jLabel.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel.setText("Airline System");

        lblTitle.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitle.setText("Passenger Login");

        lblPassengerID.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblPassengerID.setText("Passenger ID:");

        txtPassengerID.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtPassengerID.setPreferredSize(new Dimension(200, 30));

        btnLogin.setText("Login");
        btnLogin.setBackground(new Color(120, 160, 200)); // muted soft blue
        btnLogin.setForeground(Color.WHITE);
        btnLogin.setFocusPainted(false);
        btnLogin.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblNewUser.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblNewUser.setText("New User?");

        btnRegisterSwitch.setText("Register");
        btnRegisterSwitch.setBackground(new Color(135, 206, 235));
        btnRegisterSwitch.setForeground(Color.WHITE);
        btnRegisterSwitch.setFocusPainted(false);
        btnRegisterSwitch.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnRegisterSwitch.addActionListener(this::btnRegisterSwitchActionPerformed);

        // Layout
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTitle, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassengerID)
                                .addComponent(txtPassengerID, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNewUser)
                                .addComponent(btnRegisterSwitch, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        );

        layout.setVerticalGroup(
                layout.createSequentialGroup()
                        .addGap(20)
                        .addComponent(jLabel)
                        .addGap(15)
                        .addComponent(lblTitle)
                        .addGap(30)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPassengerID)
                                .addComponent(txtPassengerID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(25)
                        .addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                        .addGap(20)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNewUser)
                                .addComponent(btnRegisterSwitch, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                        .addGap(30)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String passengerID = txtPassengerID.getText().trim();

        if (passengerID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Passenger ID", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if passenger exists
        ArrayList<String[]> passengers = DataManager.readPassengers();
        boolean found = false;

        for (String[] p : passengers) {
            if (p[0].equals(passengerID)) {
                found = true;
                break;
            }
        }

        if (found) {
            JOptionPane.showMessageDialog(this, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new UserMainPage().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Passenger ID not found. Please register first.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSwitchActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RegisterPassengerPage().setVisible(true);
    }//GEN-LAST:event_btnRegisterSwitchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserLoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnLogin;
    private JButton btnRegisterSwitch;
    private JLabel jLabel;
    private JLabel lblNewUser;
    private JLabel lblPassengerID;
    private JLabel lblTitle;
    private JTextField txtPassengerID;
    // End of variables declaration//GEN-END:variables
}
