import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ashir
 */
public class ViewAllBookingsPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAllBookingsPage.class.getName());

    /**
     * Creates new form ViewAllBookingsPage
     */
    public ViewAllBookingsPage() {
        initComponents();

        // Table styling
        tblViewBookings.setEnabled(false);
        tblViewBookings.setRowHeight(28);
        tblViewBookings.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Set table header styling
        tblViewBookings.getTableHeader().setBackground(new java.awt.Color(75, 150, 255));
        tblViewBookings.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblViewBookings.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        btnRefreshBookingsActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewBookingsTitle = new javax.swing.JLabel();
        scrollViewBookings = new javax.swing.JScrollPane();
        tblViewBookings = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnRefreshBookings = new javax.swing.JButton();
        btnViewBookingsBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setBackground(new java.awt.Color(245, 250, 255));

        lblViewBookingsTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblViewBookingsTitle.setText("All Bookings");
        lblViewBookingsTitle.setForeground(new java.awt.Color(30, 30, 60));

        scrollViewBookings.setBackground(new java.awt.Color(0, 102, 102));

        tblViewBookings.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                        "Ticket ID", "Passenger Name", "CNIC", "Contact", "Flight ID",
                        "Source", "Destination", "Date", "Time", "Class", "Seat", "Price"
                }
        ));
        tblViewBookings.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblViewBookings.setShowGrid(true);
        tblViewBookings.setGridColor(new java.awt.Color(200, 200, 200));
        scrollViewBookings.setViewportView(tblViewBookings);

        jPanel1.setBackground(new java.awt.Color(245, 250, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        btnRefreshBookings.setText("Refresh Bookings");
        btnRefreshBookings.setBackground(new java.awt.Color(75, 150, 255));
        btnRefreshBookings.setForeground(java.awt.Color.WHITE);
        btnRefreshBookings.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnRefreshBookings.setFocusPainted(false);
        btnRefreshBookings.addActionListener(this::btnRefreshBookingsActionPerformed);

        btnViewBookingsBack.setText("Back");
        btnViewBookingsBack.setBackground(new java.awt.Color(200, 50, 50));
        btnViewBookingsBack.setForeground(java.awt.Color.WHITE);
        btnViewBookingsBack.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnViewBookingsBack.setFocusPainted(false);
        btnViewBookingsBack.addActionListener(this::btnViewBookingsBackActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnRefreshBookings, 200, 200, 200)
                                .addGap(50)
                                .addComponent(btnViewBookingsBack, 100, 100, 100)
                                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRefreshBookings, 40, 40, 40)
                                        .addComponent(btnViewBookingsBack, 40, 40, 40))
                                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(lblViewBookingsTitle)
                                        .addComponent(scrollViewBookings, 900, 900, 900)
                                        .addComponent(jPanel1, 900, 900, 900))
                                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblViewBookingsTitle)
                                .addGap(30, 30, 30)
                                .addComponent(scrollViewBookings, 250, 250, 250)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel1, 100, 100, 100)
                                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshBookingsActionPerformed
        ArrayList<String[]> tickets = DataManager.readTickets();

        DefaultTableModel model = (DefaultTableModel) tblViewBookings.getModel();
        model.setRowCount(0);

        for (String[] t : tickets) {
            model.addRow(t);
        }
    }//GEN-LAST:event_btnRefreshBookingsActionPerformed

    private void btnViewBookingsBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookingsBackActionPerformed
        this.dispose();
        new AdminDashboard().setVisible(true);
    }//GEN-LAST:event_btnViewBookingsBackActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new ViewAllBookingsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshBookings;
    private javax.swing.JButton btnViewBookingsBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblViewBookingsTitle;
    private javax.swing.JScrollPane scrollViewBookings;
    private javax.swing.JTable tblViewBookings;
    // End of variables declaration//GEN-END:variables
}
